### ISSUE TITLE
Non-standart e-mail types and unknown tags on Android

### ISSUE THREAD

**Issue by SauronfromMordor** [DarkHobbit/doublecontact#13]
Hello!
I use Android smartphone on Cyanogenmod 5.1.1. After I exported my contacts to VCF and opened it in DoubleContact, it showed me next:
![2017-03-08-025942_1280x1024_scrot](https://cloud.githubusercontent.com/assets/24421310/23683949/db390098-03ac-11e7-8c9e-388e63277414.png)
Could you fix it? Here is this file in TXT (rename it to VCF back).
[00001.txt](https://github.com/DarkHobbit/doublecontact/files/826230/00001.txt)

**Comment by DarkHobbit** [comment]
It's only warning, after it, such emails processed correctly. But you are right: non-standard emails (not phones) are allowed by RFC. I shall fix this warning.Thanks.

**Comment by DarkHobbit** [comment]
For emails: fixed, message removed (commit e8f7e81381d50aa55fc91c0a6d7fa347359d394e).
For phones: message appears, but you can switch it off in settings dialog, "Loading" section. Note that some devices may incorrectly work with non-standard types (most dangerous case is non-latin type names).
