### ISSUE TITLE
DEB package doesn't show info about install size

### ISSUE THREAD

**Issue by SauronfromMordor** [DarkHobbit/doublecontact#14]
Hello! When I install the DoubleContact DEB package from here (https://github.com/DarkHobbit/doublecontact/releases/download/0.1.2/doublecontact_0.1.2-jessie_amd64.deb), it doesn't show install size as opposed to other programs.
![1](https://cloud.githubusercontent.com/assets/24421310/25533667/0af79140-2c3a-11e7-94da-a4d4d3e796d6.png)

**Comment by DarkHobbit** [comment]
Fixed in make-deb-pkg script.
