### ISSUE TITLE
Icon bug (and typo)

### ISSUE THREAD

**Issue by SauronfromMordor** [DarkHobbit/doublecontact#15]
DoubleContact shows something unknown instead of its blue icon in the taskbar. Lubuntu 16.04 x64.
P.S. There is the typo in the header: "Double Contact".
![2](https://cloud.githubusercontent.com/assets/24421310/25533865/c1fc56be-2c3a-11e7-8aed-19443dde0357.png)

**Comment by SauronfromMordor** [comment]
I've made fix for typo in the headbar (https://github.com/DarkHobbit/doublecontact/pull/20). Icon is already fixed, so after merging the PR, this issue can be closed.

**Comment by DarkHobbit** [comment]
Done.
