### ISSUE TITLE
Error: "Can't read file" by double-click

### ISSUE THREAD

**Issue by SauronfromMordor** [DarkHobbit/doublecontact#16]
When I open file by double-click, I get the message:
![1](https://cloud.githubusercontent.com/assets/24421310/25543107/deb5fd28-2c5d-11e7-933f-2441e0541925.png)
And after pressing OK, DoubleContact opens being empty.
![2](https://cloud.githubusercontent.com/assets/24421310/25543146/ff0e0f16-2c5d-11e7-8087-f08ef821aefc.png)
But if I just launch DoubleContact and open this file by File-Open, it opens correctly.
![3](https://cloud.githubusercontent.com/assets/24421310/25543199/2cead702-2c5e-11e7-81e8-c62e791dd167.png)
Changing permissions doesn't help. Example: [00001.txt](https://github.com/DarkHobbit/doublecontact/files/826230/00001.txt)
Lubuntu 16.04 x64.

**Comment by DarkHobbit** [comment]
IMHO, this is because your file manager (PCManFM?) creates URL with file:// protocol prefix. I shall try to process this prefix in program, thanks.

**Comment by DarkHobbit** [comment]
Commited. Can you build DEB for your distribution from sources and check this bug? If no, simply wait next binary release (0.1.3 or 0.2).

**Comment by DarkHobbit** [comment]
Bug.

**Comment by SauronfromMordor** [comment]
Yeah, but could you add build instructions to readme like

> sudo apt-get install <...>
> mkdir build
> cd build
> ../configure --prefix=/usr/
> make

because there is "use qmake" and I don't know how.

**Comment by DarkHobbit** [comment]
Yes, I think about it.
Currently, DoubleContact depends of Qt and zlib-devel, but Qt dev libraries can have very differ names even in deb-based distribution.

**Comment by SauronfromMordor** [comment]
I've built it on Lubuntu, this fix works, I guess, but it should be better to wait 0.1.3 for re-test.
Also I've added build instructions on Ubuntu: https://github.com/DarkHobbit/doublecontact/pull/18

**Comment by DarkHobbit** [comment]
Thanks! I shall see this doc later.

**Comment by DarkHobbit** [comment]
Done.
