### ISSUE TITLE
Подсказки в программе

### ISSUE THREAD

**Issue by burunduk** [DarkHobbit/doublecontact#3]
Не хватает сплывающих подсказок над некоторыми полями. Например "имя".
При добавлении поля имя не явно указано, где имя/фамилия отчество.

**Comment by DarkHobbit** [comment]
Про имя/фамилия отчество - да, это недоработка, вообще-то. С другой стороны, я насмотрелся на то, что поля эти все лепят в каком хотят порядке. Хотя в RFC явно определены все 5 компонентов имени, да и функция перестановки имён у меня именно для того, чтобы приводить их в порядок. Подумаю, как добавить метки, не загромождая пространство...

**Comment by DarkHobbit** [comment]
В частности имени - исправил. Теперь все 5 компонентов имени снабжены метками, как в диалоге редактирования, так и в диалоге сравнения. (Можно, кстати, обновить перевод, т.к. не все компоненты имени были раньше поименованы - ну и другие новшества там есть.)
А вот именно _всплывающие_ подсказки - их вроде бы у меня и нет нигде вообще. А надо? Можно этим заморочиться, просто назначение большинства полей очевидно из подписи/метки. Ну и для переводчиков это означает распухание перевода раза так в полтора...

**Comment by burunduk** [comment]
Спасибо!
