### ISSUE TITLE
Некорректная работа со свойством CATEGORIES

### ISSUE THREAD

**Issue by dwlttpr** [DarkHobbit/doublecontact#39]
В vCard уже есть стандартизированное свойство CATEGORIES (https://en.wikipedia.org/wiki/VCard), в нём разделителем тегов является запятая.

Doublecontact использует свойство X-CATEGORIES с разделителем ';'.  Doublecontact может вычитать и свойство CATEGORIES, но разделителем будет считаться также ';'.

Также наблюдается замена CATEGORIES на  X-CATEGORIES во всей адресной книге при редактировании групп для хотя бы одного контакта.

Отличие проявилось при импорте адресной книги в Nextcloud.

[ссылка на описание CATEGORIES в rfc](https://tools.ietf.org/html/rfc6350#section-6.7.1)

**Comment by DarkHobbit** [comment]
Замена CATEGORIES на X-CATEGORIES происходит в случае, если версия vCard выходного файла задана 2.1 или 3.0 (задаётся в настройках). CATEGORIES введён только в vCard 4.0.
С разделителями проверю.

**Comment by DarkHobbit** [comment]
Исправлено в коммите 8e0bba8. Теперь при записи тега CATEGORIES разделитель - запятая, кроме случаев работы с файлами MPB. Устаревший тег X-CATEGORIES поддерживается только на чтение.
К сожалению, андроид-устройства не воспринимают тег CATEGORIES при импорте из файлов VCF, он работает только через облачные сервисы (Google или упомянутый выше Nextcloud). Некоторые телефоны используют для групп нестандартный тег X-GROUP-MEMBERSHIP.
