### ISSUE TITLE
Необязательность нумерации

### ISSUE THREAD

**Issue by DarkHobbit** [DarkHobbit/doublecontact#4]
Сделать столбец с номерами записей отключаемым ввиду его малой информативности. (Идея cheshire_cat, linux.org.ru). Взамен, вероятно, выводить количество записей в строке состояния.

**Comment by burunduk** [comment]
И, пожалуйста, дабавить остальные столбцы. Описание, аську и т.п.

**Comment by DarkHobbit** [comment]
Идея здравая, хотя по-хорошему, это бы в отдельное issue... Ладно, увидим и здесь.
