### ISSUE TITLE
NICKNAME type in vCard 3.0 is not saved properly

### ISSUE THREAD

**Issue by keshonok** [DarkHobbit/doublecontact#41]
[vCard 3.0 specification](https://www.ietf.org/rfc/rfc2426.txt) has `NICKNAME` property. `Settings`->`Saving`->`Preferred vCard Version` is set to `3.0`. However, this property is saved as `X-NICKNAME`.

There's `Add X- to type names` setting for non-standard phone/email types in the same `Setting`->`Saving` tab. Its state doesn't appear to have any effect on this (not that it should, it's just I am not sure).

Also, the entry field for `NICKNAME` is located in the `Internet` tab which is sort of counter-intuitive. I believe it should better be placed in the first `General` tab somewhere near the section `Name`.

**Comment by DarkHobbit** [comment]
Fixed in 7eca2e7. NICKNAME used already for write.
Note, that some devices write X-NICKNAME even in vCard 3.0. DoubleContact still support this tag for read.
