### ISSUE TITLE
Use the ellipsis symbol instead of three detached dots

### ISSUE THREAD

**Issue by NathanBnm** [DarkHobbit/doublecontact#43]
You have to use the ellipsis symbol instead of three detached dots.

**Comment by DarkHobbit** [comment]
This is not simple a question. Yes, ellipsis has more nice look, but...
First contra argument: without ellipsis symbols program source is latin-only and more portable. With ellipsis symbols, it will be UTF-8, and may cause problems on some old systems.
Second contra argument: replacement or existing strings break links with translations. Old strings will be loss, and translators must work on this strings from start.
I not speak "no". It is subject for discussion. But currently, more practical place ellipsis symbols in translation files, not in C++ source. I shall think about it.

I must decide this before 0.2.2 release!

**Comment by NathanBnm** [comment]
I understand your point.

However I think it's always better to use UTF-8 encoding, especially if you're app is available for translation.

Maybe you can avoid the issue with translations by making a search and replace operation in your files.

**Comment by DarkHobbit** [comment]
All ellipsis symbols moved into translation files (including English). It's portable decision for ellipsis use.
