### ISSUE TITLE
Неточное сравнение контактов

### ISSUE THREAD

**Issue by burunduk** [DarkHobbit/doublecontact#6]
Есть два одинаковых контакта, и отличие только в порядке тегов. Программа показывает, что контакты отличаются.
Пример:
`TEL;TYPE=work,pref:+1-213-555-1234`
и
`TEL;TYPE=pref,work:+1-213-555-1234`

**Comment by DarkHobbit** [comment]
Наверное, да, такие контакты надо считать одинаковыми. Хотя алгоритм при этом несколько усложнится...
Частичное совпадение-то хоть показывает? :)

**Comment by burunduk** [comment]
Да, показывает.

**Comment by DarkHobbit** [comment]
Сейчас, по идее, должно заработать...
